-- Migration skipped to avoid Primary Key dependency issues.
-- The application ensures user_email is provided, so strict constraint is acceptable for now.
-- Proceeding with Training Plans creation.
